### ISSUE TITLE
Override NS Window

### ISSUE THREAD

**Issue by noisiak** [eppz/Unity.Blog.Override_App_Delegate#1]
I wonder if is possible to also override NS Windows and be able to control things like the NS Window Title Bar (to hide it, change color or make in invisible).

**Comment by Geri-Borbas** [comment]
Sure you can get a reference to the main window of the app (see [`NSApplication.mainWindow`](https://developer.apple.com/documentation/appkit/nsapplication/1428723-mainwindow)), and set its properties. I think with a regular plugin you can do that, no need for overriding app delegate.
