### ISSUE TITLE
EPPZSwizzler.m Expected a type

### ISSUE THREAD

**Issue by tom-willmowski** [eppz/Unity.Blog.Override_App_Delegate#2]
```
+(void)synthesizePropertyNamed:(NSString*) propertyName
                        ofKind:(Class) kind
                      forClass:(Class) targetClass
                    withPolicy:(EPPZSwizzlerProperryAssociationPolicy) policy
{
    // Get type encoding.
    const char *typeEncoding = @encode(typeof(kind)); // Expected a type
```

I'm not able to compile a project.

**Comment by Coeur** [comment]
Just to clarify, are you talking about:
- the iOS file (iOS/Override_iOS/Override_iOS/EPPZSwizzler.{h,m})?
- or the macOS file (OSX/Override_OSX/Override_OSX/EPPZSwizzler.{h,m})?

**Comment by Geri-Borbas** [comment]
[This change](https://github.com/eppz/Unity.Blog.Override_App_Delegate/pull/7/commits/64d7434701a2e9330def66822b6a32bcfd500bac) probably suppresses this error.
