### ISSUE TITLE
Undefined symbol

### ISSUE THREAD

**Issue by yosun** [eppz/Unity.Blog.Override_App_Delegate#6]
Showing Recent Messages
Undefined symbol: _DeepLink_GetSourceApplication

Undefined symbol: _DeepLink_GetURL

Undefined symbol: _DeepLink_Reset

**Comment by yosun** [comment]
libOverride_iOS.a seems to be for OS X and not for iOS?

**Comment by Geri-Borbas** [comment]
There is a chance that it was built for OSX last time.
Feel free to open the project and recompile for any OS of your choice.

**Comment by yosun** [comment]
Yes, fixed it for you. Accept the pull requests. https://github.com/eppz/Unity.Blog.Override_App_Delegate/pull/7/files
