### ISSUE TITLE
For DeepLink SendMessage is probably better than Update loop call

### ISSUE THREAD

**Issue by yosun** [eppz/Unity.Blog.Override_App_Delegate#8]
For DeepLink SendMessage is probably better than Update loop call

**Comment by Geri-Borbas** [comment]
The entire purpose of this library is to catch "application-launching deep link opens". 

If I recall right, Unity services like `SendMessage` are not available at `didFinishLaunchingWithOptions:` time. This entire dance with `UserDefaults` is a workaround to attack that issue. I recommend to read up the articles references in [`README.md`](https://github.com/eppz/Unity.Blog.Override_App_Delegate/blob/master/README.md). Although it is not deep link focused, I'm sure the corresponding considerations are there somewhere along the line.

**Comment by yosun** [comment]
calling a plugin every frame in the update loop is disgustingly expensive. 
here's what you should be using: https://docs.unity3d.com/ScriptReference/MonoBehaviour.OnApplicationFocus.html

**Comment by Geri-Borbas** [comment]
Thanks, sounds definitely better. I think I tried that back then, but there were some app-switching use cases when it did not get invoked (or not in time).
